<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-06-29 at 06:14:56.
 */
class cMysqlTest extends PHPUnit_Framework_TestCase {

    /**
     * @var cMysql
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new cMysql;

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers cMysql::getConnection
     * @todo   Implement testGetConnection().
     */
    public function testGetConnection() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );

    }

    /**
     * @covers cMysql::read
     * @todo   Implement testRead().
     */
    public function testRead() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );

    }

    /**
     * @covers cMysql::write
     * @todo   Implement testWrite().
     */
    public function testWrite() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );

    }

    /**
     * @covers cMysql::getNextVal
     * @todo   Implement testGetNextVal().
     */
    public function testGetNextVal() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );

    }

    /**
     * @covers cMysql::getCurrVal
     * @todo   Implement testGetCurrVal().
     */
    public function testGetCurrVal() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );

    }

    /**
     * @covers cMysql::getColumnDetails
     * @todo   Implement testGetColumnDetails().
     */
    public function testGetColumnDetails() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );

    }

    /**
     * @covers cMysql::getChildTables
     * @todo   Implement testGetChildTables().
     */
    public function testGetChildTables() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );

    }

    /**
     * @covers cMysql::getTableDetails
     * @todo   Implement testGetTableDetails().
     */
    public function testGetTableDetails() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );

    }

    /**
     * @covers cMysql::getForeignKeyDetails
     * @todo   Implement testGetForeignKeyDetails().
     */
    public function testGetForeignKeyDetails() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );

    }

}
