<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-06-29 at 06:14:55.
 */
class cSqlTest extends PHPUnit_Framework_TestCase {

    /**
     * @var cSql
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new cSql;

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * Generated from @assert ($this->query) == "".
     *
     * @covers cSql::resetQuery
     */
    public function testResetQuery() {
        $this->assertEquals(
                ""
                , $this->object->resetQuery($this->query)
        );

    }

    /**
     * @covers cSql::create
     * @todo   Implement testCreate().
     */
    public function testCreate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );

    }

    /**
     * @covers cSql::createmultiple
     * @todo   Implement testCreatemultiple().
     */
    public function testCreatemultiple() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );

    }

    /**
     * @covers cSql::read
     * @todo   Implement testRead().
     */
    public function testRead() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );

    }

    /**
     * @covers cSql::update
     * @todo   Implement testUpdate().
     */
    public function testUpdate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );

    }

    /**
     * @covers cSql::alter
     * @todo   Implement testAlter().
     */
    public function testAlter() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );

    }

    /**
     * @covers cSql::delete
     * @todo   Implement testDelete().
     */
    public function testDelete() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );

    }

    /**
     * @covers cSql::addWhereCondition
     * @todo   Implement testAddWhereCondition().
     */
    public function testAddWhereCondition() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );

    }

    /**
     * @covers cSql::addGroupBy
     * @todo   Implement testAddGroupBy().
     */
    public function testAddGroupBy() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );

    }

    /**
     * @covers cSql::addHaving
     * @todo   Implement testAddHaving().
     */
    public function testAddHaving() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );

    }

    /**
     * @covers cSql::addOrderBy
     * @todo   Implement testAddOrderBy().
     */
    public function testAddOrderBy() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );

    }

    /**
     * @covers cSql::addLimit
     * @todo   Implement testAddLimit().
     */
    public function testAddLimit() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );

    }

    /**
     * @covers cSql::addOffsetBy
     * @todo   Implement testAddOffsetBy().
     */
    public function testAddOffsetBy() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );

    }

    /**
     * @covers cSql::getColumnDetails
     * @todo   Implement testGetColumnDetails().
     */
    public function testGetColumnDetails() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );

    }

    /**
     * @covers cSql::getTableDetails
     * @todo   Implement testGetTableDetails().
     */
    public function testGetTableDetails() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );

    }

    /**
     * @covers cSql::getNextVal
     * @todo   Implement testGetNextVal().
     */
    public function testGetNextVal() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );

    }

    /**
     * @covers cSql::getChildTables
     * @todo   Implement testGetChildTables().
     */
    public function testGetChildTables() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );

    }

}
